os:
  - linux
language: cpp
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get -y install libz-dev libpng-dev libsfml-dev libfreetype6-dev libglew-dev
    liblua5.2-dev libglu1-mesa-dev
  - mkdir build
  - cd build
  - cmake ..
script: sudo make install
env:
  global:
    - secure: "gdjWNg+TWRh5SwqtKe0g2R4iOGWifOUIT3ucinnUMdJ80mJGfttWpmbvOEMvCUqsfzvsaoTyeEeQ11Ps1sqItQ1QeRAU0j3YG9K4ZMfwKdl6x5rX7XjpshbsR8XccJhkopWo+ZkSTHTkCxtfcZJ8O6yqJSC6Vb595pAwxiV2S4GeK5eFnHk6NQpaR6U33q18Yt07PAeMcG+cgX88A8BixurT3FFZG6j3w/yIduTIvOiWQ44tbn++UWsaHamhlAuE5jKmk5p9ZkJsg9p0GiQosNMEDmylV/J2BdbiCSG9VHt2GFNl2g0CHhHHN6kcBDIPlGKA9AqJEUlJA8YhNUAHZ41NjuhRq7K9hzv4g8V/YyVj9rUn5gOmcw2+udb7vBP8cayOZfMoKsHTYGhmKj8eULQJ3Qyuf06zueWozpZGwsKD7XStnUfC6ZHQUJm2ZHETRC80H9UouCv7KgzpLtP/4ysJImwOd7KI5MmTJkOikTmpLuAvaQ6BVVkT36tyWuVRJKr7jYyWsZia6kV+y0X3EDcnnS08RTYBi49Ap58WqJI/IjVjdE+mpTQOt/A8OQh6JepWTA+PzZn+Q7bcXA1cr3kR7HA06BmCx2kEKEOS/4Zsyv8Bwwm48qMYBKXb1pY8ICoYVvH43P6mOfEuqYP9HTf16Tk1TuB78jszrbXeujs="
jobs:
  include:
    - stage: deploy
      os: linux
      compiler: gcc
      before_script:
        - sudo apt-get -y install doxygen
      script:
        - if [[ "$TRAVIS_BRANCH" != "master" ]]; then travis_terminate 0; fi
        - if [[ "$TRAVIS_PULL_REQUEST" = "true" ]] ; then travis_terminate 0; fi
        - cd $TRAVIS_BUILD_DIR
        - .ci/setup-git.sh || travis_terminate 1
        - .ci/generate-doc.sh || travis_terminate 1
